import React, { useState, useEffect } from 'react';
import { Scanner } from '@yudiel/react-qr-scanner';
import api from '../../api/client';

export default function QRCodeScanner({ isOpen, onClose, onSuccess, onError }) {
  const [scanning, setScanning] = useState(false);
  const [locationStatus, setLocationStatus] = useState('Getting location...');

  if (!isOpen) return null;

  const handleScan = async (result) => {
    if (scanning || !result || result.length === 0) return;
    
    try {
      setScanning(true);
      
      // Robust token extraction
      const token = result[0]?.rawValue || result?.text || (typeof result === 'string' ? result : null);
      if (!token) {
        onError('Could not read QR code. Please try again.');
        setScanning(false);
        return;
      }

      setLocationStatus('Verifying location...');
      
      // Check if Geolocation is supported/available
      if (!navigator.geolocation) {
        console.warn('Geolocation API is not available (might require HTTPS or localhost). Bypassing frontend location requirement for testing, backend will still enforce if required.');
        // Proceed without location if we can't get it at all due to browser restrictions
        // The backend will handle the missing location gracefully (either allow or deny based on its rules)
        onSuccess(token, null, null);
        return;
      }
      
      // Get location
      navigator.geolocation.getCurrentPosition(
        async (position) => {
          try {
            const { latitude, longitude } = position.coords;
            onSuccess(token, latitude, longitude);
          } catch (error) {
            console.error('API Error during QR scan:', error);
            onError(error.response?.data?.message || 'Failed to process QR code');
            setScanning(false);
          }
        },
        (error) => {
          console.warn('Geolocation error (fallback to null):', error);
          onSuccess(token, null, null);
        },
        { enableHighAccuracy: true, timeout: 5000, maximumAge: 0 }
      );
    } catch (err) {
      console.error(err);
      onError('An error occurred while scanning: ' + err.message);
      setScanning(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
      <div className="bg-surface-container rounded-3xl w-full max-w-md overflow-hidden shadow-2xl flex flex-col">
        <div className="p-4 border-b border-outline-variant flex justify-between items-center bg-surface">
          <h2 className="text-lg font-bold text-on-surface">Scan DTR QR Code</h2>
          <button 
            onClick={onClose}
            className="w-8 h-8 flex items-center justify-center rounded-full hover:bg-surface-container-highest text-on-surface-variant transition-colors"
          >
            <span className="material-symbols-outlined text-[20px]">close</span>
          </button>
        </div>
        
        <div className="p-6 flex flex-col items-center">
          {scanning ? (
            <div className="flex flex-col items-center py-12 text-center gap-4">
              <span className="material-symbols-outlined text-vibrant-orange text-4xl animate-spin">refresh</span>
              <div>
                <p className="font-bold text-on-surface">{locationStatus}</p>
                <p className="text-xs text-on-surface-variant mt-1">Please wait while we verify your scan.</p>
              </div>
            </div>
          ) : (
            <>
              <p className="text-sm text-center text-on-surface-variant mb-6">
                Scan the QR code generated by your Workplace Mentor to record your attendance. Make sure you are within the organization's premises.
              </p>
              <div className="w-full max-w-[280px] aspect-square rounded-2xl overflow-hidden border-2 border-vibrant-orange/30 shadow-inner relative bg-black">
                <Scanner 
                  onScan={handleScan}
                  onError={(err) => {
                    console.error('Scanner error:', err);
                  }}
                  components={{
                    audio: false,
                    finder: false
                  }}
                  styles={{
                    container: { width: '100%', height: '100%' },
                    video: { objectFit: 'cover' }
                  }}
                />
                
                {/* Overlay finder */}
                <div className="absolute inset-0 pointer-events-none border-[40px] border-black/40 flex items-center justify-center">
                  <div className="w-full h-full border-2 border-vibrant-orange rounded-xl"></div>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
