import React, { useState, useEffect } from 'react';
import { Scanner } from '@yudiel/react-qr-scanner';
import api from '../../api/client';

export default function QRCodeScanner({ isOpen, onClose, onSuccess, onError }) {
  const [scanning, setScanning] = useState(false);
  const [locationStatus, setLocationStatus] = useState('Getting location...');

  if (!isOpen) return null;

  const handleScan = async (result) => {
    if (scanning || !result || result.length === 0) return;
    
    try {
      setScanning(true);
      const token = result[0].rawValue;
      setLocationStatus('Verifying location...');
      
      // Get location
      navigator.geolocation.getCurrentPosition(
        async (position) => {
          try {
            const { latitude, longitude } = position.coords;
            
            // Check if we need to clock in or clock out
            // Since we don't know the exact endpoint to call from just the token,
            // we will let the backend handle the logic based on the student's current status.
            // Wait, our backend has /attendance/clock-in and /attendance/clock-out
            // If the student is already clocked in today without clocking out, we call clock-out.
            // Actually, we can just call an endpoint, or pass the token to the parent so the parent calls it.
            // But we need to pass lat and lng to the parent.
            onSuccess(token, latitude, longitude);
          } catch (error) {
            console.error('API Error during QR scan:', error);
            onError(error.response?.data?.message || 'Failed to process QR code');
            setScanning(false);
          }
        },
        (error) => {
          let errorMsg = 'Location error';
          if (error.code === 1) errorMsg = 'Location permission denied. Please allow location access to clock in.';
          if (error.code === 2) errorMsg = 'Location unavailable. Please try again.';
          if (error.code === 3) errorMsg = 'Location request timed out. Please try again.';
          onError(errorMsg);
          setScanning(false);
        },
        { enableHighAccuracy: true, timeout: 10000, maximumAge: 0 }
      );
    } catch (err) {
      console.error(err);
      onError('An error occurred while scanning.');
      setScanning(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
      <div className="bg-surface-container rounded-3xl w-full max-w-md overflow-hidden shadow-2xl flex flex-col">
        <div className="p-4 border-b border-outline-variant flex justify-between items-center bg-surface">
          <h2 className="text-lg font-bold text-on-surface">Scan DTR QR Code</h2>
          <button 
            onClick={onClose}
            className="w-8 h-8 flex items-center justify-center rounded-full hover:bg-surface-container-highest text-on-surface-variant transition-colors"
          >
            <span className="material-symbols-outlined text-[20px]">close</span>
          </button>
        </div>
        
        <div className="p-6 flex flex-col items-center">
          {scanning ? (
            <div className="flex flex-col items-center py-12 text-center gap-4">
              <span className="material-symbols-outlined text-vibrant-orange text-4xl animate-spin">refresh</span>
              <div>
                <p className="font-bold text-on-surface">{locationStatus}</p>
                <p className="text-xs text-on-surface-variant mt-1">Please wait while we verify your scan.</p>
              </div>
            </div>
          ) : (
            <>
              <p className="text-sm text-center text-on-surface-variant mb-6">
                Scan the QR code generated by your Workplace Mentor to record your attendance. Make sure you are within the organization's premises.
              </p>
              <div className="w-full max-w-[280px] aspect-square rounded-2xl overflow-hidden border-2 border-vibrant-orange/30 shadow-inner relative bg-black">
                <Scanner 
                  onScan={handleScan}
                  onError={(err) => {
                    console.error('Scanner error:', err);
                  }}
                  components={{
                    audio: false,
                    finder: false
                  }}
                  styles={{
                    container: { width: '100%', height: '100%' },
                    video: { objectFit: 'cover' }
                  }}
                />
                
                {/* Overlay finder */}
                <div className="absolute inset-0 pointer-events-none border-[40px] border-black/40 flex items-center justify-center">
                  <div className="w-full h-full border-2 border-vibrant-orange rounded-xl"></div>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
