import React, { useState, useEffect } from 'react';
import { Scanner } from '@yudiel/react-qr-scanner';
import { getLocation, scanQR, isNative } from '../../services/platform';

export default function QRCodeScanner({ isOpen, onClose, onSuccess, onError }) {
  const [scanning, setScanning] = useState(false);
  const [locationStatus, setLocationStatus] = useState('Getting location...');
  const [useWebFallback, setUseWebFallback] = useState(false);

  // Reset fallback on modal open
  useEffect(() => {
    if (isOpen) {
      setUseWebFallback(false);
      setScanning(false);
    }
  }, [isOpen]);

  // For native, we auto-trigger the scanner when modal opens
  useEffect(() => {
    if (isOpen && isNative && !useWebFallback) {
      (async () => {
        try {
          const token = await scanQR();
          if (token && typeof token === 'string') {
            await processScanResult(token);
          } else if (token === false) {
            // Native scanner unresolvable, fall back to embedded web scanner
            setUseWebFallback(true);
          } else {
            // User cancelled scan cleanly
            onClose();
          }
        } catch (err) {
          console.warn('[QRCodeScanner] Native scanner notice:', err.message);
          setUseWebFallback(true);
        }
      })();
    }
  }, [isOpen, useWebFallback]);

  if (!isOpen) return null;

  const processScanResult = async (token) => {
    if (scanning || !token) return;
    
    try {
      setScanning(true);
      setLocationStatus('Verifying location...');
      
      try {
        const coords = await getLocation();
        onSuccess(token, coords.lat, coords.lng);
      } catch (error) {
        console.warn('Geolocation error (fallback to null):', error);
        onSuccess(token, null, null);
      }
    } catch (err) {
      console.error(err);
      onError('An error occurred while scanning: ' + err.message);
      setScanning(false);
    }
  };

  const handleWebScan = async (result) => {
    if (!result || result.length === 0) return;
    
    const token = result[0]?.rawValue || result?.text || (typeof result === 'string' ? result : null);
    if (!token) {
      return;
    }
    await processScanResult(token);
  };

  const showWebScanner = !isNative || useWebFallback;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in">
      <div className="bg-surface-container rounded-3xl w-full max-w-md overflow-hidden shadow-2xl flex flex-col border border-outline-variant">
        <div className="p-4 border-b border-outline-variant flex justify-between items-center bg-surface">
          <h2 className="text-lg font-bold text-on-surface">Scan DTR QR Code</h2>
          <button 
            onClick={onClose}
            className="w-8 h-8 flex items-center justify-center rounded-full hover:bg-surface-container-highest text-on-surface-variant transition-colors cursor-pointer"
          >
            <span className="material-symbols-outlined text-[20px]">close</span>
          </button>
        </div>
        
        <div className="p-6 flex flex-col items-center">
          {scanning ? (
            <div className="flex flex-col items-center py-12 text-center gap-4">
              <span className="material-symbols-outlined text-vibrant-orange text-4xl animate-spin">refresh</span>
              <div>
                <p className="font-bold text-on-surface">{locationStatus}</p>
                <p className="text-xs text-on-surface-variant mt-1">Please wait while we verify your scan.</p>
              </div>
            </div>
          ) : (
            <>
              <p className="text-xs sm:text-sm text-center text-on-surface-variant mb-6 leading-relaxed">
                Scan the QR code generated by your Workplace Mentor to record your attendance. Make sure you are within the organization's premises.
              </p>
              
              {showWebScanner ? (
                <div className="w-full max-w-[280px] aspect-square rounded-2xl overflow-hidden border-2 border-vibrant-orange/30 shadow-inner relative bg-black flex items-center justify-center">
                  <Scanner 
                    onScan={handleWebScan}
                    onError={(err) => console.warn('Web scanner error:', err)}
                    components={{ audio: false, finder: false }}
                    styles={{
                      container: { width: '100%', height: '100%' },
                      video: { objectFit: 'cover' }
                    }}
                  />
                  <div className="absolute inset-0 pointer-events-none border-[40px] border-black/40 flex items-center justify-center">
                    <div className="w-full h-full border-2 border-vibrant-orange rounded-xl"></div>
                  </div>
                </div>
              ) : (
                <div className="py-8 flex flex-col items-center justify-center gap-3">
                   <span className="material-symbols-outlined text-6xl text-vibrant-orange animate-pulse">qr_code_scanner</span>
                   <p className="font-bold text-sm text-on-surface">Launching native scanner...</p>
                   <button
                     type="button"
                     onClick={() => setUseWebFallback(true)}
                     className="mt-2 text-xs text-vibrant-orange font-bold hover:underline cursor-pointer"
                   >
                     Use Screen Camera Scanner
                   </button>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
